- name: Ensure ufw stopped and disabled
  tags:
    - install
    - configure
  service:
    name: ufw
    state: stopped
    enabled: false
#OMNI-7941 Added when condition to exclude Oracle Linux distros, due to them usuing NetworkManager as the default network service
- name: Ensure Network manager stopped and disabled
  tags:
    - install
    - configure
  service:
    name: systemd-networkd
    state: stopped
    enabled: false
  when: (ansible_facts['distribution'] != "OracleLinux")
