name: Run ansible playbook

on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest

    environment: creds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          
      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.yml -t install playbook.yml --private-key=~/.ssh/id_rsa --limit=bastion
